edit Jenkinsfile

diff --git a/lab2/Jenkinsfile b/lab2/Jenkinsfile
--- a/lab2/Jenkinsfile
+++ b/lab2/Jenkinsfile
@@ -2,21 +2,54 @@ pipeline {
     agent any
 
     stages {
-        stage('AAAAAAAAAAAAAAAAAAAAAA') {
+        stage('Setup Python Environment') {
             steps {
-                sh 'cat /usr/share/doc/python3.11/README.venv'
-                sh 'pip3 list'
-                echo '---------------------'
-                echo "Dependency installation..."
-                sh 'python3 -m venv venv'
-                sh 'ls'
-                echo '---------------------'
-                sh 'chmod +x venv/bin/activate'
-                sh './venv/bin/activate'
-                sh 'pip3 list'
-                echo '---------------------'
-                sh 'python3 -m pip install -r lab2/requirements.txt --break-system-packages'
-                echo "Dependencies installed."
+                script {
+                    echo 'Creating a virtual environment, if not already created'
+                    sh '''
+                        if [ ! -d ".venv" ]; then
+                            env_name=${1:-".venv"}
+                            python3 -m venv "$env_name"
+                            echo "The virtual environment '$env_name' has been created."
+                        fi
+                    '''
+
+                    echo 'Activating the virtual environment'
+                    sh '''
+                        env_name=${1:-".venv"}
+                        if [ ! -d "$env_name" ]; then
+                            echo "Virtual environment '$env_name' not found. Use '$0 create [env_name]' to create."
+                            return 1
+                        fi
+                        if [ -z "$VIRTUAL_ENV" ]; then
+                            chmod +x ./$env_name/bin/activate
+                            ./$env_name/bin/activate
+                            echo "Virtual environment '$env_name' is activated."
+                        else
+                            echo "The virtual environment has already been activated."
+                        fi
+                    '''
+
+                    echo 'Dependency installation'
+                    sh '''
+                        if [ ! -f "lab2/requirements.txt" ]; then
+                            echo "File requirements.txt not found."
+                            return 1
+                        fi
+
+                        # Check if all dependencies from requirements.txt are installed
+                        for package in $(cat lab2/requirements.txt | cut -d '=' -f 1); do
+                            if ! pip3 freeze | grep -q "^$package=="; then
+                                echo "Dependency installation..."
+                                pip3 install -r lab2/requirements.txt --break-system-packages
+                                echo "Dependencies installed."
+                                return 0
+                            fi
+                        done
+
+                        echo "All dependencies are already installed."
+                    '''
+                }
             }
         }
         stage('Generate train and test dataset') {
