edit Jenkinsfile

diff --git a/lab2/Jenkinsfile b/lab2/Jenkinsfile
--- a/lab2/Jenkinsfile
+++ b/lab2/Jenkinsfile
@@ -32,9 +32,51 @@ pipeline {
 
                     echo 'install dependencies'
                     sh '''
-                        cat lab2/requirements.txt
+                        if [ ! -f "lab2/requirements.txt" ]; then
+                            echo "file requirements.txt not found"
+                            return 1
+                        fi
+
+                        # check if all dependencies from requirements.txt are installed
+                        for package in $(cat lab2/requirements.txt | cut -d '=' -f 1); do
+                            if ! pip freeze | grep -q "^$package=="; then
+                                echo "dependency installation:.."
+                                pip install -r lab2/requirements.txt
+                                echo "dependencies installed"
+                                return 0
+                            fi
+                        done
+                        echo "all dependencies are already installed"
                     '''
                 }
+            }
+        }
+        stage('Generate train and test dataset') {
+            steps {
+                echo 'start generate datasets'
+                sh 'python lab2/src/data_creation.py'
+                echo 'finish generate datasets'
+            }
+        }
+        stage('Data preprocessing') {
+            steps {
+                echo 'start data preprocessing'
+                sh 'python lab2/src/model_preprocessing.py'
+                echo 'finish data preprocessing'
+            }
+        }
+        stage('Create and train model') {
+            steps {
+                echo 'start create and train model'
+                sh 'python lab2/src/model_preporation.py'
+                echo 'finish create and train model'
+            }
+        }
+        stage('Test model') {
+            steps {
+                echo 'start testing model'
+                sh 'python lab2/src/model_testing.py'
+                echo 'finish testing model'
             }
         }
     }
